[package]
name = "autonice"
version = "0.1.0"
authors = ["Bert Peters <bert@bertptrs.nl>"]

[dependencies]
libc = "^0.2.34"
xdg-basedir = "^1.0.0"
yaml-rust = "^0.3.5"
clap = {version = "^2.29.0", features = ["yaml"]}
